# -*- mode: ruby -*-

N = 1

box = "bento/amazonlinux-2"
enable_port_forwards = "no"  #Define if port forwards should be enabled
port_forwards = [
  {
    :node => "node0",
    :guest => 80,
    :host => 8080
  }
]

server_cpus = 1
server_memory = 3072

Vagrant.configure(2) do |config|
  (1..N).each do |node_id|
    nid = (node_id - 1)

    config.vm.define "node#{nid}" do |node|
      # excludes roles folder from rsync to avoid recurring symlinks
      config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: "roles/"
      node.vm.box = box
      node.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--cpus", server_cpus]
        vb.customize ["modifyvm", :id, "--memory", server_memory]
      end
      node.vm.hostname = "node#{nid}"

      if enable_port_forwards == "yes"
        port_forwards.each do |pf|
          if pf[:node] == "node#{nid}"
            node.vm.network "forwarded_port", guest: pf[:guest], host: pf[:host] + nid
          end
        end
      end

      if node_id == N
        node.vm.provision "ansible" do |ansible|  #runs bootstrap Ansible playbook
          ansible.limit = "all"
          ansible.playbook = "bootstrap.yml"
        end
        node.vm.provision "ansible" do |ansible|  #runs Ansible playbook for installing roles/executing tasks
          ansible.limit = "all"
          ansible.playbook = "run-test.yml"
        end
      end
    end
  end
end
